language: php
php:
  - '7.1'

services:
  - docker

script: 
  - docker build -t divante/pimcore-docker-php-fpm .

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push divante/pimcore-docker-php-fpm;
    fi